### ISSUE TITLE
Upgrades?

### ISSUE THREAD

**Issue by GantMan** [GantMan/jail-monkey#3]
I have tested and verified that JailMonkey works on devices, but I'm interested in these advanced detection techniques.   Perhaps I should evaluate adding them?

https://github.com/sat2eesh/ios-jailBroken/blob/master/JBroken.m

**Comment by aprct** [comment]
What about detecting if the app is running on an SD card in Android? I'm not sure about the implications, but it'd be a cool quickie to add to the list of detection features.

http://stackoverflow.com/questions/5814474/how-can-i-find-out-if-my-app-is-installed-on-sd-card

**Comment by aprct** [comment]
Ping @GantMan !

Submitted PR: https://github.com/GantMan/jail-monkey/pull/5 :)

Let me know if you think this belongs in Jail Monkey. If not, then I'll go ahead and release it under itself.

👍

**Comment by GantMan** [comment]
hey @aprct !   First thanks for an awesome PR!

I was trying to wrap my head around if this should be on Jail Monkey or not.  So the theme of jail monkey is "Trust", but if a file being on an SD card violates some kind of trust then YES!  it should be here.  If it's just interesting hardware info, it should probably be pitched over at https://github.com/rebeccahughes/react-native-device-info

Thoughts?

**Comment by aprct** [comment]
It was a tossup between this library and that one. :)

I included it here because I'm working with protected health information and protected financial information for my company. We're following OWASP guidelines [which specifically recommend having the app available only on non-rooted/jailbroken devices and not on SD cards](https://www.owasp.org/index.php/Mobile_Top_10_2016-Top_10). Therefore, it _is_ a matter of trust to us and many other finance/health companies that have tighter controls in place.

That said, I can think of a few edge cases off the top of my head where apps that don't need as much security would still benefit from knowing whether or not it's running on external storage. :)

Your call!

**Comment by GantMan** [comment]
makes sense!
